version: '3.8'

services:
  backend:
    build: .
    expose:
      - "3000"
    networks:
      - app-net
    deploy:
      replicas: 1 # Start with 1 replica, and you can scale it up as needed
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
      placement:
        constraints:
          - node.role == worker # Ensure it runs on worker nodes

  redis:
    image: redis:latest
    networks:
      - app-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == worker

  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == worker

networks:
  app-net:
    driver: overlay
